# Generated by Django 3.2.9 on 2021-12-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceCode', '0009_auto_20211203_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='time',
            field=models.CharField(default='16:22:03', max_length=15),
        ),
    ]
