name: Django CI

on:
  push:
    branches: [ unittests ]
    paths-ignore: '**/SkoleProtocol/attendanceCode/tests/test_selenium.py'
  pull_request:
    branches: [ unittests ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234!
          MYSQL_DATABASE: Skoleprotocol
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS Skoleprotocol;'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 ./attendanceCode --exit-zero # Exit with status code "0" even if there are errors.
    - name: Django Tests
      run: |
        python3 manage.py test